language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: "lorenzobettini-github"
    token:
      secure: $SONAR_TOKEN

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - git fetch --unshallow --quiet
   - mvn -f simple-sonarqube-example/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
